### ISSUE TITLE
TypeError("example() missing 1 required positional argument: 'auth'",)

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [kianxineki/bottlejwt#6]
I've tried to run the example code in the README file, but I always get the error

        TypeError("example() missing 1 required positional argument: 'auth'",)

how do I get this working?

**Comment by agalera** [comment]
you must call the API, not the function directly

for example:
```python
import requests


requests.get('http://localhost:9988', headers={'Authorization': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGVwaXRvIn0.WSu6TVa5GZnBxj4OsCvcGEcbu55AMiQxz1xU3qPLKIw'})
```

this works with the example
